# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular subject in the app', primary_key=True, serialize=False)),
                ('subject_name', models.CharField(help_text='Name of the subject to track', max_length=20)),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular subtopic in the app', primary_key=True, serialize=False)),
                ('subtopic_name', models.CharField(help_text='Name of the topic to track', max_length=20)),
            ],
            options={
                'ordering': ['subtopic_name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular topic in the app', primary_key=True, serialize=False)),
                ('topic_name', models.CharField(help_text='Name of the topic to track', max_length=20)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Subject')),
            ],
            options={
                'ordering': ['topic_name'],
            },
        ),
        migrations.AddField(
            model_name='subtopic',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Topic'),
        ),
    ]
