# Generated by Django 2.0.2 on 2018-02-19 17:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1000)])),
                ('covered', models.BooleanField(default=True)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Subject')),
                ('subtopic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Subtopic')),
            ],
            options={
                'ordering': ['covered'],
            },
        ),
    ]
