# Generated by Django 2.0.1 on 2018-02-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
