# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-29 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='subtopic_name',
            field=models.CharField(help_text='Name of the topic to track', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(help_text='Name of the topic to track', max_length=60),
        ),
    ]
