# Generated by Django 2.0.2 on 2018-02-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='tracker',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Student'),
            preserve_default=False,
        ),
    ]
