# Generated by Django 2.0.1 on 2018-02-19 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180219_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('Resourceid', models.IntegerField(help_text='Unique ID for each resource', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1000)])),
                ('resource_name', models.CharField(help_text='Name of the resource', max_length=60)),
                ('subtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Subtopic')),
            ],
            options={
                'ordering': ['Resourceid'],
            },
        ),
    ]
